# -*- coding: utf-8 -*-

"""
   uberapilib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = "https://api.uber.com/v1"

    # The OAuth 2.0 access token to be set before API calls
    # TODO: Replace the o_auth_access_token with an appropriate value
    o_auth_access_token = "TODO: Replace"


