# -*- coding: utf-8 -*-

"""
    uberapilib.uber_api_client

    This file was automatically generated by APIMATIC BETA v2.0 on 07/19/2016
"""

from uberapilib.http import *
from uberapilib.models import *
from uberapilib.controllers import *
from uberapilib.decorators import *
from uberapilib.api_exception import *

class UberAPIClient(object):

    @lazy_property
    def client(self):
        return APIController()



