# -*- coding: utf-8 -*-

"""
    uberapilib.models.meta
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
"""

from uberapilib.models.base_model import BaseModel
from uberapilib.models.surge_confirmation import SurgeConfirmation

class Meta(BaseModel):

    """Implementation of the 'meta' model.

    TODO: type model description here.

    Attributes:
        surge_confirmation (SurgeConfirmation): TODO: type description here.

    """

    def __init__(self, 
                 surge_confirmation = None):
        """Constructor for the Meta class"""
        
        # Initialize members of the class
        self.surge_confirmation = surge_confirmation

        # Create a mapping from Model property names to API property names
        self.names = {
            "surge_confirmation": "surge_confirmation",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            surge_confirmation = SurgeConfirmation.from_dictionary(dictionary.get("surge_confirmation")) if dictionary.get("surge_confirmation") else None
            # Return an object of this model
            return cls(surge_confirmation)
