# -*- coding: utf-8 -*-

"""
    uberapilib.models.product_collection
 
    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/19/2016
"""

from uberapilib.models.base_model import BaseModel
from uberapilib.models.product import Product

class ProductCollection(BaseModel):

    """Implementation of the 'Product Collection' model.

    Collection of products

    Attributes:
        products (list of Product): List of products

    """

    def __init__(self, 
                 products = None):
        """Constructor for the ProductCollection class"""
        
        # Initialize members of the class
        self.products = products

        # Create a mapping from Model property names to API property names
        self.names = {
            "products": "products",
        }

    @classmethod
    def from_dictionary(cls, 
                        dictionary):
        """Creates an instance of this model from a dictionary
       
        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.
            
        Returns:
            object: An instance of this structure class.
            
        """

        if dictionary == None:
            return None
        else:	
            # Extract variables from the dictionary
            products = None
            if dictionary.get("products") != None:
                products = list()
                for structure in dictionary.get("products"):
                    products.append(Product.from_dictionary(structure))
            # Return an object of this model
            return cls(products)
